version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - run: make docker_build
workflows:
  basic:
    jobs:
      - build-and-test